FROM node:7.10

LABEL maintainer "Stan Chollet <stanislas.chollet@gmail.com>"

RUN apt-get update && apt-get install apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install yarn

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/

RUN yarn

COPY .babelrc /usr/src/app/
COPY .eslintrc /usr/src/app/
COPY config.toml /usr/src/app/
COPY gatsby-browser.js /usr/src/app/
COPY gatsby-node.js /usr/src/app/
COPY gatsby-ssr.js /usr/src/app/
COPY html.js /usr/src/app/

COPY ./src /usr/src/app/src
COPY ./pages /usr/src/app/pages
COPY ./wrappers /usr/src/app/wrappers
COPY ./loaders /usr/src/app/loaders

CMD [ "npm", "start" ]